const CONFIG = {
  SHEETS: {
    PRODUCTS_TCG: {
      name: "ProductsTCG",
      headers: [
        "game",
        "id",
        "cardCode",
        "name",
        "displayName",
        "image",
        "rarity",
        "cardType",
        "set",
        "subtypes",
        "priceUsd",
        "tcgPlayerUrl",
      ],
    },
    INVENTORY: {
      name: "Inventory",
      headers: [
        "game",
        "id",
        "cardCode",
        "name",
        "displayName",
        "image",
        "rarity",
        "cardType",
        "priceUsd",
        "stock",
        "set",
        "subtypes",
        "tcgPlayerUrl",
      ],
    },
    VOUCHERS: {
      name: "Vouchers",
      headers: [
        "code",
        "type",
        "scope",
        "value",
        "maxUses",
        "usedCount",
        "expiresAt",
        "allowedTiers",
        "active",
      ],
    },
    /** @deprecated kept for older spreadsheets */
    SHIPPING_RULES: {
      name: "ShippingRules",
      headers: ["minSubtotal", "shippingFee"],
    },
    SHIPPING_TIERS: {
      name: "ShippingTiers",
      headers: ["customerTier", "shippingFee", "note"],
    },
    ORDERS: {
      name: "Orders",
      headers: [
        "orderCode",
        "createdAt",
        "facebookName",
        "customerTier",
        "note",
        "shippingFee",
        "discountCode",
        "total",
      ],
    },
    ORDER_ITEMS: {
      name: "OrderItems",
      headers: [
        "orderCode",
        "productId",
        "cardCode",
        "productName",
        "price",
        "quantity",
        "rarity",
        "lineTotal",
        "source",
      ],
    },
    SETTINGS: {
      name: "Settings",
      headers: ["key", "value"],
    },
  },
  STYLE: {
    MAX_COLUMN_WIDTH: 200,
    HEADER_TEXT_COLOR: "#1F2937",
    HEADER_COLORS: [
      "#DBEAFE",
      "#E0E7FF",
      "#EDE9FE",
      "#FCE7F3",
      "#FEE2E2",
      "#FEF3C7",
      "#DCFCE7",
      "#D1FAE5",
      "#E0F2FE",
    ],
    ODD_ROW_COLOR: "#FFFFFF",
    EVEN_ROW_COLOR: "#F8FAFC",
  },
  SCRIPT_PROPERTIES: {
    API_TOKEN: "API_TOKEN",
  },
  CACHE: {
    PRODUCTS_TCG_KEY: "products_tcg_v1",
    INVENTORY_KEY: "inventory_v1",
    SETTINGS_KEY: "settings_v1",
    TTL_SECONDS: 600,
    /** Script Cache value limit is 100 KB; stay below to avoid put() errors. */
    MAX_VALUE_BYTES: 90000,
    CHUNK_SUFFIX: ":chunk:",
    META_SUFFIX: ":meta",
  },
  DEFAULT_LIST_LIMIT: 50,
  MAX_LIST_LIMIT: 200,
  DEFAULTS: {
    USD_VND_RATE: 25000,
    PRICE_MULTIPLIER: 1.1,
    SHIPPING_FEE: 36000,
    TCG_ORDER_STOCK: 999,
  },
};
